# Generated by Django 2.0.1 on 2018-01-28 17:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1900)])),
                ('season', models.CharField(choices=[('RABI', 'rabi'), ('KHARIF', 'kharif')], default='rabi', max_length=6)),
                ('geo_farm', models.CharField(default='', max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('number_of_farms', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=200)),
                ('geo_field', models.CharField(default='', max_length=1000000)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krishiyog.farm')),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krishiyog.farmer'),
        ),
    ]
