# Generated by Django 2.0.1 on 2018-01-29 18:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishiyog', '0003_worldborder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='geo_farm',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
