# Generated by Django 2.0.1 on 2018-01-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishiyog', '0004_auto_20180129_1834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorldBorder',
        ),
    ]
