# Generated by Django 2.0.1 on 2018-01-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishiyog', '0005_delete_worldborder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_name',
            field=models.CharField(max_length=30),
        ),
    ]
