# Generated by Django 2.0.1 on 2018-01-30 07:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishiyog', '0006_auto_20180130_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='geo_field',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
