# Generated by Django 2.0.1 on 2018-01-30 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishiyog', '0007_auto_20180130_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='season',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='year',
        ),
        migrations.AddField(
            model_name='field',
            name='season',
            field=models.CharField(choices=[('RABI', 'rabi'), ('KHARIF', 'kharif')], default='rabi', max_length=6),
        ),
        migrations.AddField(
            model_name='field',
            name='year',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1900)]),
        ),
    ]
